### get all products
GET http://localhost:4000/api/products/62518b484aecc0fad823e06b
###  
POST http://localhost:4000/api/products/create
Content-Type: application/json
{
    "title":"google pixel",
    "price":"RS.10000",
    "image":"https://google.com",
    "details":"blue,128 GB Storage"
}
###
GET http://localhost:4000/api/products
###
DELETE http://localhost:4000/api/products/62518b484aecc0fad823e06b  HTTP/1.1
